context:
  name: healpix-geo
  version: "0.0.6"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/eopf-dggs/healpix-geo/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 88ee6fe9c018387580a0dff03c04e3dae9b65ac3cf002418f5fc659a2db1bde4

build:
  skip:
    - match(python, "<3.10")
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - python -m pip install . -vv --no-build-isolation --no-deps
  number: 2

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.7.0,<2.0
    - cargo-bundle-licenses
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
  host:
    - python
    - maturin >=1.7.0,<2.0
    - pip
  run:
    - python
    - numpy

tests:
  - python:
      imports:
        - healpix_geo
        - healpix_geo.nested
        - healpix_geo.ring
        - healpix_geo.slices
      pip_check: true

about:
  homepage: https://github.com/eopf-dggs/healpix-geo
  summary: 'healpix for the geo-sciences'
  description: |
    healpix-geo uses the cdshealpix, moc, and geodesy crates to provide
    specialized algorithms for the geosciences.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://healpix-geo.readthedocs.io/
  repository: https://github.com/eopf-dggs/healpix-geo

extra:
  recipe-maintainers:
    - keewis
