context:
  name: healpix-geo
  version: "0.2.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/grid4earth/healpix-geo/archive/refs/tags/v${{ version }}.tar.gz
  sha256: be27371c9d51ade19df5a60082f4106571376c986d6cb59d83019726b2e61736

build:
  skip:
    - is_abi3 and not is_python_min
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - python -m pip install python/healpix-geo -vv --no-build-isolation --no-deps
  python:
    version_independent: ${{ is_abi3 }}
  number: 1

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - maturin >=1.7.0,<2.0
    - cargo-bundle-licenses
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('rust') }}
  host:
    - python
    - maturin >=1.7.0,<2.0
    - pip
  run:
    - python
    - numpy
    - marray-python

tests:
  - python:
      imports:
        - healpix_geo
        - healpix_geo.nested
        - healpix_geo.ring
        - healpix_geo.zuniq
        - healpix_geo.geometry
        - healpix_geo.auto
      pip_check: true

about:
  homepage: https://github.com/grid4earth/healpix-geo
  summary: 'healpix for the geo-sciences'
  description: |
    healpix-geo uses the cdshealpix, moc, and geodesy crates to provide
    specialized algorithms for the geosciences.
  license: Apache-2.0
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://healpix-geo.readthedocs.io/
  repository: https://github.com/grid4earth/healpix-geo

extra:
  recipe-maintainers:
    - keewis
